manheim/manheim-c7n-tools

.readthedocs.yml, docs/requirements.txt, tox.ini
The code changes in #5 [broke the ReadTheDocs build](https://readthedocs.org/projects/manheim-c7n-tools/builds/9251629/) because building docs now requires the ``m2r`` package. Refactor requirements handling for RTD builds so that RTD will properly install the requirements.
=> fix ReadTheDocs build

README.md, docker-compose.test.yml, dockertest.sh, docs/source/manheim_c7n_tools.errorscan.rst, docs/source/manheim_c7n_tools.rst, docs/source/runner.rst, docs/source/usage.rst, manheim_c7n_tools/errorscan.py, setup.py
This is the last bit of internal python that we have wrapped around c7n - the ``errorscan`` script which checks the CloudWatch Metrics and Logs, and SQS Dead Letter Queue, for all c7n Lambda functions in one account/region, and reports on any errors or failed executions. I can't find anything Manheim-specific in this, so it makes sense to me to add it to this image.
Copied from internal code.
=> Add errorscan script

CHANGES.rst, README.md, manheim_c7n_tools/version.py, setup.py
The README / description is broken [on PyPI](https://pypi.org/project/manheim-c7n-tools/) because I omitted the markdown content type. This fixes it.
=> Pypi readme fix

CHANGES.rst, manheim_c7n_tools/policygen.py, manheim_c7n_tools/tests/test_utils.py, manheim_c7n_tools/utils.py, manheim_c7n_tools/version.py
There's a bug we hadn't hit in our internal code, where ``policygen`` dies when running under python3 because it tries to use a string regex on a unicode/bytes value. This PR fixes that.
Unit tests.
=> fix unicode encoding error when running under py3

CHANGES.rst, manheim_c7n_tools/dryrun_diff.py, manheim_c7n_tools/version.py
When running ``dryrun-diff`` locally this morning in a Python3 venv, I found 2 bugs in it: one related to Python3 and one related to running the standalone ``dryrun-diff`` entrypoint vs running it as a step in ``manheim-c7n-runner``. 
Ran locally; bugs fixed.
=> fix dryrun-diff errors

.gitignore, docs/source/policies.rst, docs/source/policygen.rst, example_config_multi_repo/README.rst, example_config_multi_repo/manheim-c7n-tools.yml, example_config_multi_repo/policies/app/defaults.yml, example_config_multi_repo/policies/app/one-account/us-east-1/ec2-low-utilization-mark.yml, example_config_multi_repo/policies/defaults.yml, example_config_multi_repo/policies/shared/all_accounts/common/ami-old-used-report.yml, example_config_multi_repo/policies/shared/one-account/common/c7n-cw-log-retention.yml, example_config_multi_repo/policies/shared/one-account/common/ebs-attachment-info-tag.yml, example_config_multi_repo/policies/team/one-account/common/c7n-cw-log-retention.yml, example_config_multi_repo/policies/team/one-account/common/ebs-unattached-delete.yml, example_config_multi_repo/policies/team/one-account/us-east-2/ec2-low-utilization-mark.yml, example_config_multi_repo/policies/team/one-account/us-west-2/ec2-low-utilization-mark.yml, manheim_c7n_tools/config.py, manheim_c7n_tools/policygen.py, manheim_c7n_tools/tests/test_policygen.py, setup.py
Updates to policygen to allow aggregating multiple policy directories via a new
configuration entry. A new configuration value was added,
`policy_source_paths`, which are assumed to be relative to the `policies`
subdirectory. They are processed in the order listed in the configuration file,
with rules of the same name in later paths taking precedence over those in
earlier paths.
Defaults are treated in a similar way, with a `defaults.yml` in a later path
overriding those in an earlier path. If none of the source paths have
a `defaults.yml`, it will be taken from the `policies` directory.
Local testing was performed on a new rules repo with multiple configurations,
examinging the output to confirm that rules were generated properly.
A test repo is being configured for use in verification …
=> Update policygen to allow aggregating multiple source paths.

docs/source/policies.rst
A link to an example of a multi-repo layout was commented out in a previous PR
(#12), as that PR was going to create the link target. This PR re-establishes
the link now that the previous PR is mergedp.
Local docs build
* I have the legal power and …
=> Uncomment doc link to multi repo example

.travis.yml, CHANGES.rst, manheim_c7n_tools/version.py, setup.py, tox.ini
Bumps c7n to the latest release version. Drops support for testing with python2. Fixes tests due to mock package incompatibilities with version 4.x.
https://travis-ci.org/github/manheim/manheim-c7n-tools/builds/664895816
_Optional; instructions to reviewers, plans for how to release this, dependencies in other repos, etc._
this pull request grants a perpetual, global, unlimited license for it …
=> Bumps c7n to latest release

CHANGES.rst, manheim_c7n_tools/errorscan.py, manheim_c7n_tools/version.py
Right now, the ``errorscan`` script expects the dead letter SQS queue (for c7n-mailer) to exist in whatever region errorscan is running in. This results in an unhandled exception for environments where c7n-mailer is only deployed into one region. This PR changes it to log a warning, but continue, if the SQS queue can't be found.
In an account where c7n-mailer and its SQS queues are only deployed into us-east-1:
on master, running errorscan in us-east-2:
```
$ errorscan -v -A -c ~/tmp/manheim-c7n-tools.yml myacct us-east-2
2020-04-01 12:00:13,673 INFO:manheim_c7n_tools.config:Loading config from: /home/jantman/tmp/manheim-c7n-tools.yml
Traceback (most recent call last):
File "/home/jantman/manheim/git/github_dot_com/manheim-c7n-tools/venv/bin/errorscan", line 11, in <module> …
```
=> 0.8.4 - warn on missing dead letter queue instead of dying

CHANGES.rst, example_config_multi_repo/manheim-c7n-tools.yml, example_config_repo/manheim-c7n-tools.yml, manheim_c7n_tools/config.py, manheim_c7n_tools/runner.py, manheim_c7n_tools/tests/test_config.py, manheim_c7n_tools/tests/test_runner.py, manheim_c7n_tools/version.py
This PR rolls up fixes for two issues:
* #23 - the ``cleanup_notify`` config parameter was required but undocumented. This PR documents it, and also makes it optional with a default of an empty list.
* #24 - we previously _required_ the ``us-east-1`` region to be configured and run first out of all regions. The only reason I could find for this (aside from it's where we happen to run mailer, but that's just a convention of ours internally) is we used it to ensure that we only run the Policygen and Docs Generation steps once, in the first region. However, we could instead just run them in the first-configured region (first ``config.regions`` list item). That's what this PR does.
Unit tests.
=> Issue fixes

CHANGES.rst, manheim_c7n_tools/policygen.py, manheim_c7n_tools/tests/test_policygen.py, manheim_c7n_tools/version.py
The previous release has a critical bug where mailer-templates are looked for in ``<additional_source_repo>/mailer-templates`` instead of ``policies/<additional_source_repo>/mailer-templates``, and therefore never found.
Unit tests and local manual testing.
=> Fix bug in 0.8.5 - mailer template loading logic was missing policies directory prefix

CHANGES.rst, manheim_c7n_tools/runner.py, manheim_c7n_tools/tests/test_runner.py, manheim_c7n_tools/version.py
* Previously, manheim-c7n-tools set c7n-mailer's ``templates_folders`` configuration option (where to find the c7n-mailer templates) to ``/manheim_c7n_tools/manheim_c7n_tools/mailer-templates`` if that directory exists, or to the absolute path to a ``mailer-templates`` directory inside the ``manheim_c7n_tools`` installation otherwise. This behavior was largely based on the legacy hard-coded templates directory. Now that c7n-mailer template locations are more flexible, and version 0.8.5 of this tool added the ability to layer templates into ``./mailer-templates``, this behavior has been updated to (in order of evaluation):
* Use the ``templates_folders`` option from the ``mailer_config`` section of ``manheim-c7n-tools.yml``, if present. Otherwise, start with an empty list.
* Prepend …
=> Templates folders

CHANGES.rst, manheim_c7n_tools/dryrun_diff.py, manheim_c7n_tools/policygen.py, manheim_c7n_tools/tests/test_policygen.py, manheim_c7n_tools/version.py
``policygen`` generates an RST file listing each policy, its description (comment), and which accounts and regions it runs in. This does not, however, take into account the policy layering provided by ``policy_source_paths``.
After this PR, if ``policy_source_paths`` is specified and non-empty, the ``policies.rst`` file generated by policygen will include an additional ``Source Path(s)`` column showing which source paths each policy came from.
* Unit tests
* Manual tests - see below
```rst
+-----------------------------------------------+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| Policy Name                                   | Account(s) / Region(s)   | …
```
=> if policy_source_paths is specified, include the policy sources in policies.rst

CHANGES.rst, manheim_c7n_tools/version.py, setup.py
This PR adds the ``m2r`` (markdown 2 rst) package as a dependency, as it is helpful during the ``docs`` build step.
None. Just added a dependency. Local testing only.
=> Add m2r dependency

docs/source/policies.rst
Docs update to fix #30 - clarify that policy names must match their filenames.
=> Fixes #30 - Docs - clarify that policy name must match filename

.travis.yml, CHANGES.rst, manheim_c7n_tools/runner.py, manheim_c7n_tools/tests/test_runner.py, manheim_c7n_tools/vendor/mugc.py, manheim_c7n_tools/version.py, setup.py, tox.ini
This PR updates our c7n and c7n-mailer versions to the latest releases, and also bumps TravisCI testing from py36/py37 to py37/py38.
Note that ``vendor/mugc.py`` has been copied directly from upstream.
* Automated unit tests and Docker build
* dry-run using this image with an internal repo; see link in Slack
=> Update c7n and c7n-mailer versions, bump Python versions used for Travis tests

.dockerignore, CHANGES.rst, Dockerfile, manheim_c7n_tools/version.py, requirements.txt, setup.py
The mailer in this project / Docker image is currently broken because of upstream https://github.com/cloud-custodian/cloud-custodian/issues/5707 where c7n-mailer failed to declare its dependency on ``jsonpointer`` and ``jsonpatch``, causing mailer to fail to run. This was fixed in https://github.com/cloud-custodian/cloud-custodian/pull/5708 upstream, which has been merged to master but not yet released (the release will be done whenever https://github.com/cloud-custodian/cloud-custodian/pull/5734 is merged).
This PR goes back to installing c7n and c7n-mailer from upstream git, in order to pull in this fix. Once there's a new upstream release, we'll revert these changes and bump to the latest upstream version.
Automated tests via tox show the install is now pulling in ``jsonpatch==1.25`` …
=> Install from git, to get fix for missing jsonpointer and jsonpatch deps

CHANGES.rst, dockertest.sh, manheim_c7n_tools/tests/test_runner.py, manheim_c7n_tools/version.py, requirements.txt
This bumps the version of c7n that we're installing from upstream git to [b62af99](https://github.com/cloud-custodian/cloud-custodian/commit/b62af99171bf1163413d7f7411e4a0db8a50f27e) in order to pull in [PR \#5751](https://github.com/cloud-custodian/cloud-custodian/pull/5751), fix for [\#5750](https://github.com/cloud-custodian/cloud-custodian/issues/5750) c7n-mailer critical bug.
It also adds a unit test to ensure that the upstream mailer archive generation works so we don't have a bug like this before.
Unit tests and automated build.
=> Fixes #41 - fix for mailer exception

CHANGES.rst, manheim_c7n_tools/version.py
This adds a CHANGES entry for the merge of #34 and also bumps the version to 1.0.0, in recognition of our extensive use internally.
Automated tests.
=> changelog for PR #34 merge, and version bump to 1.0.0

.gitignore, docs/source/policygen.rst, manheim_c7n_tools/policygen.py, manheim_c7n_tools/tests/test_policygen.py
Currently, merging rulesets does not properly replace existing rules with new ones. Instead, it merges the rules
together resulting in potentially nonsense rules.
The current implementation does not properly replace existing rules from layered rulesets.
This PR fixes that issue, as well as adding the ability to disable rules from higher-level rulesets completely.
Local testing, as well as new tox tests for both disabling rules and merging rulesets.
* My contribution may perpetually be …
=> Add ability to disable rules, as well as fix a bug in ruleset merging.

CHANGES.rst, docs/source/policygen.rst
The docs had the correct name for disabling policies. It should be just `disable`. 
* I have the legal power and rights to agree to these terms.
=> Update docs to reflect new 'disable' option

CHANGES.rst, manheim_c7n_tools/version.py, requirements.txt, setup.py
Release v1.2.1
Pull pinned c7n commit to resolve issue of Splunk HEC source type not being configurable. See https://github.com/cloud-custodian/cloud-custodian/pull/5893
* I have the legal power and rights to agree to these terms.
=> Release v1.2.1

CHANGES.rst, manheim_c7n_tools/version.py, requirements.txt, setup.py
* Bump c7n to release 0.9.4
* Bump c7n-mailer to release 0.6.3
* Updated dependencies for c7n and c7n-mailer
* I have the legal power and rights to agree to these terms.
=> Bumping c7n to latest release

CHANGES.rst, docs/source/policies.rst, example_config_multi_repo/policies/shared/all_accounts/common/disabled-rule.yml, example_config_multi_repo/policies/team/one-account/common/disabled-rule.yml, example_config_repo/policies/one-account/common/disabled-rule.yml, manheim_c7n_tools/policygen.py, manheim_c7n_tools/tests/test_policygen.py, manheim_c7n_tools/version.py
This PR adds support for documenting disabled rules to the generated policy documentation.
New unit tests, local testing using the example repos included in this project. A new disabled rule was added to both example sets.
* I have the legal power …
=> Add `disable` state to generated policy documentation

CHANGES.rst, manheim_c7n_tools/config.py, manheim_c7n_tools/errorscan.py, manheim_c7n_tools/policygen.py, manheim_c7n_tools/runner.py, manheim_c7n_tools/tests/test_config.py, manheim_c7n_tools/tests/test_policygen.py, manheim_c7n_tools/tests/test_runner.py, manheim_c7n_tools/version.py, pytest.ini, setup.cfg, tox.ini
c7n allows a configurable Lambda function name prefix, which defaults to ``custodian-``. For the policies, this is configured in the actual policy YML. However, for mugc garbage collection, it needs to be explicitly passed in. In the current release, we have mugc hard-coded to the default of ``custodian-``. The result of this, as described in #53, is that manheim-c7n-tools can provision policies with a non-default prefix but mugc keeps trying to clean up the default-prefixed policies.
This PR solves this issue with 3 pieces:
1. A new ``function_prefix`` option in ``manheim-c7n-tools.yml``, which defaults to the current and upstream default of ``custodian-``.
2. Modify ``MugcStep`` to use that configuration option instead of the hard-coded ``custodian-``.
3. Add a new policy sanity check …
=> Fixes #53 - mugc not respecting function_prefix

.travis.yml, CHANGES.rst, Dockerfile, manheim_c7n_tools/version.py, requirements.txt, setup.py, tox.ini
This PR fixes #56 by bumping both c7n and c7n-mailer to their latest upstream releases. It also adds python 3.9 test runs, and bumps the base Docker image from python 3.7 to 3.9.
TBD.
=> Bump to latest c7n and c7n-mailer releases

README.md
travis-ci.org is being shut down. I've migrated this repo from .org to .com. This PR updates the README accordingly.
travis-ci.com tests
=> update README for migration to travis-ci.com

.travis.yml, CHANGES.rst, docs/source/development.rst, docs/source/manheim_c7n_tools.notifyonly.rst, docs/source/manheim_c7n_tools.rst, docs/source/policies.rst, docs/source/policygen.rst, manheim_c7n_tools/notifyonly.py, manheim_c7n_tools/policygen.py, manheim_c7n_tools/tests/test_config.py, manheim_c7n_tools/tests/test_notifyonly.py, manheim_c7n_tools/tests/test_policygen.py, manheim_c7n_tools/tests/test_runner.py, manheim_c7n_tools/tests/test_utils.py, tox.ini
This PR implements ``notify_only`` support for policies, which can also be used in ``defaults.yml`` to put an entire account into notify-only mode. This is controlled by a ``notify_only`` boolean top-level policy key, which policygen then handles and strips out when generating the final custodian YAML files.
The current functionality of notify-only is as follows:
-   The `comment` / `comments` / `description` fields will be prefixed with the string `NOTIFY ONLY:`
-   If the policy has a `tags` list, a `notify-only` tag will be appended to it.
-   All tagging actions will have the string `-notify-only` appended to their tag names, to automate the above-described transition. Specifically:
-   Any `mark` or `tag` actions in the actions list will have the string `-notify-only` appended to …
=> Implement notify-only support
